apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  db-password: "password" # Should be changed in production
  jwt-secret: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkey"
